version: "3.8"

services:
  # ---------- SQLite single-instance (local/dev) ----------
  app-sqlite:
    build: .
    image: task-scheduler:sqlite
    container_name: task-scheduler-sqlite
    environment:
      - SINGLE_INSTANCE=true
      - USE_JOBSTORE=false
      - SCHED_DB_PATH=/data/tasks.db
      - POLL_INTERVAL_SECONDS=30
      - DEFAULT_MAX_RETRIES=3
      - DEFAULT_RETRY_DELAY=60
      - PORT=5000
    volumes:
      - ./data/sqlite:/data          # persistent tasks.db file
      - ./:/usr/src/app:ro           # optional: mount code read-only (useful for quick dev)
    ports:
      - "5001:5000"                  # expose app-sqlite on host:5001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  # ---------- Postgres DB for multi-instance / production ----------
  postgres:
    image: postgres:15
    container_name: task-scheduler-postgres
    environment:
      - POSTGRES_USER=psuser
      - POSTGRES_PASSWORD=pspass
      - POSTGRES_DB=tasksdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------- App configured to use Postgres jobstore ----------
  app-postgres:
    build: .
    image: task-scheduler:postgres
    container_name: task-scheduler-postgres
    depends_on:
      - postgres
    environment:
      - SINGLE_INSTANCE=false
      - USE_JOBSTORE=true
      - # SQLAlchemy URL for Postgres jobstore (APScheduler) and DB_PATH used also by app metadata code
      - DB_PATH=postgresql://psuser:pspass@postgres:5432/tasksdb
      - POLL_INTERVAL_SECONDS=30
      - DEFAULT_MAX_RETRIES=3
      - DEFAULT_RETRY_DELAY=60
      - PORT=5000
    ports:
      - "5002:5000"                  # expose app-postgres on host:5002
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  postgres-data:
